# Generated by Django 5.0.4 on 2024-04-13 19:14

from django.db import migrations


def create_categories_default(apps, schema_editor):
    Category = apps.get_model("core", "Category")
    name_categories = [
        "Novo Produto",
        "Troca de Fornecedor",
        "Reformulação de Produto",
    ]
    for name in name_categories:
        Category.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_categories_default),
    ]
