name: Django CI with Docker

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8
        run: flake8 .

      - name: Run Black (check mode)
        run: black --check .

      - name: Run tests with coverage
        run: |
          cd briefing_management
          coverage run manage.py test
          coverage report --fail-under=70

      - name: Build and run the Docker container
        run: |
          docker build -t web .
          docker run -d -p 8000:8000 web
